apiVersion: v1
kind: Service
metadata:
  name: mediwatch-inference-api-service
spec:
  selector:
    app: mediwatch-inference-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
